server:
  shutdown: graceful
spring:
  application.name: northwind
  output.ansi.enabled: always
  profiles.active: dev  # TODO. change profile to prod
  lifecycle:
    timeout-per-shutdown-phase: 30s
logging:
  level:
    root: info
    # org.springframework.security: DEBUG
    com.djccnt15.northwind:
      domain: trace
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID}){magenta} --- [%clr(${spring.application.name:-unknown}){yellow}] [%-30.30t] [%8X{traceId:-}] %clr(%-40.40logger{39}){cyan} : %m%n%ex"
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p ${PID} --- [${spring.application.name:-unknown}] [%-30.30t] [%8X{traceId:-}] %-40.40logger{39} : %m%n%ex"
app:
  defaultPw: 1234
  loginFailureLimit: 6
