spring:
  jpa:
    # show-sql: true # use logging.level.org.hibernate.SQL=debug instead
    properties.hibernate:
      format_sql: true
      highlight_sql: true
      use_sql_comment: true
logging:
  level:
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace
